# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_qt.ui'
#
# Created: Wed Nov 16 14:37:48 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_sourceConnectMainWindow(object):
    def setupUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setObjectName("sourceConnectMainWindow")
        sourceConnectMainWindow.resize(1196, 834)
        self.centralwidget = QtGui.QWidget(sourceConnectMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tagFrame = QtGui.QFrame(self.centralwidget)
        self.tagFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tagFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tagFrame.setObjectName("tagFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.tagFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagBox = QtGui.QGroupBox(self.tagFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.tagBox.setFont(font)
        self.tagBox.setFlat(False)
        self.tagBox.setCheckable(False)
        self.tagBox.setObjectName("tagBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.tagBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tagLineEdit = QtGui.QLineEdit(self.tagBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagLineEdit.setFont(font)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.gridLayout_8.addWidget(self.tagLineEdit, 0, 2, 1, 1)
        self.tagSearchButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagSearchButton.sizePolicy().hasHeightForWidth())
        self.tagSearchButton.setSizePolicy(sizePolicy)
        self.tagSearchButton.setMinimumSize(QtCore.QSize(45, 0))
        self.tagSearchButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagSearchButton.setFont(font)
        self.tagSearchButton.setObjectName("tagSearchButton")
        self.gridLayout_8.addWidget(self.tagSearchButton, 0, 3, 1, 1)
        self.superTagButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.superTagButton.sizePolicy().hasHeightForWidth())
        self.superTagButton.setSizePolicy(sizePolicy)
        self.superTagButton.setMinimumSize(QtCore.QSize(45, 0))
        self.superTagButton.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.superTagButton.setFont(font)
        self.superTagButton.setStatusTip("")
        self.superTagButton.setObjectName("superTagButton")
        self.gridLayout_8.addWidget(self.superTagButton, 0, 0, 1, 1)
        self.subTagButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subTagButton.sizePolicy().hasHeightForWidth())
        self.subTagButton.setSizePolicy(sizePolicy)
        self.subTagButton.setMinimumSize(QtCore.QSize(45, 0))
        self.subTagButton.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.subTagButton.setFont(font)
        self.subTagButton.setStatusTip("")
        self.subTagButton.setObjectName("subTagButton")
        self.gridLayout_8.addWidget(self.subTagButton, 0, 1, 1, 1)
        self.clearTagsButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearTagsButton.sizePolicy().hasHeightForWidth())
        self.clearTagsButton.setSizePolicy(sizePolicy)
        self.clearTagsButton.setMinimumSize(QtCore.QSize(45, 0))
        self.clearTagsButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.clearTagsButton.setFont(font)
        self.clearTagsButton.setObjectName("clearTagsButton")
        self.gridLayout_8.addWidget(self.clearTagsButton, 0, 4, 1, 1)
        self.tagListWidget = QtGui.QListWidget(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagListWidget.sizePolicy().hasHeightForWidth())
        self.tagListWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tagListWidget.setFont(font)
        self.tagListWidget.setObjectName("tagListWidget")
        self.gridLayout_8.addWidget(self.tagListWidget, 1, 0, 1, 5)
        self.gridLayout_2.addWidget(self.tagBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.tagFrame, 0, 0, 1, 1)
        self.sourcesFrame = QtGui.QFrame(self.centralwidget)
        self.sourcesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourcesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourcesFrame.setObjectName("sourcesFrame")
        self.gridLayout_5 = QtGui.QGridLayout(self.sourcesFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sourcesBox = QtGui.QGroupBox(self.sourcesFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.sourcesBox.setFont(font)
        self.sourcesBox.setFlat(False)
        self.sourcesBox.setCheckable(False)
        self.sourcesBox.setObjectName("sourcesBox")
        self.gridLayout_7 = QtGui.QGridLayout(self.sourcesBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.sourceLineEdit = QtGui.QLineEdit(self.sourcesBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceLineEdit.setFont(font)
        self.sourceLineEdit.setObjectName("sourceLineEdit")
        self.gridLayout_7.addWidget(self.sourceLineEdit, 0, 0, 1, 1)
        self.sourcesSearchButton = QtGui.QPushButton(self.sourcesBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourcesSearchButton.setFont(font)
        self.sourcesSearchButton.setObjectName("sourcesSearchButton")
        self.gridLayout_7.addWidget(self.sourcesSearchButton, 0, 1, 1, 1)
        self.sourcesList = QtGui.QTreeWidget(self.sourcesBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sourcesList.setFont(font)
        self.sourcesList.setObjectName("sourcesList")
        self.sourcesList.headerItem().setText(0, "1")
        self.gridLayout_7.addWidget(self.sourcesList, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.sourcesBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourcesFrame, 1, 0, 1, 1)
        self.sourceSummaryFrame = QtGui.QFrame(self.centralwidget)
        self.sourceSummaryFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourceSummaryFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourceSummaryFrame.setObjectName("sourceSummaryFrame")
        self.gridLayout_4 = QtGui.QGridLayout(self.sourceSummaryFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SourceSummaryBox = QtGui.QGroupBox(self.sourceSummaryFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.SourceSummaryBox.setFont(font)
        self.SourceSummaryBox.setFlat(False)
        self.SourceSummaryBox.setCheckable(False)
        self.SourceSummaryBox.setObjectName("SourceSummaryBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.SourceSummaryBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtGui.QFrame(self.SourceSummaryBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 27))
        self.frame.setMaximumSize(QtCore.QSize(620, 16777215))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boldButton = QtGui.QToolButton(self.frame)
        self.boldButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.boldButton.setFont(font)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout.addWidget(self.boldButton)
        self.italicButton = QtGui.QToolButton(self.frame)
        self.italicButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(False)
        self.italicButton.setFont(font)
        self.italicButton.setObjectName("italicButton")
        self.horizontalLayout.addWidget(self.italicButton)
        self.underlineButton = QtGui.QToolButton(self.frame)
        self.underlineButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(True)
        font.setBold(False)
        self.underlineButton.setFont(font)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout.addWidget(self.underlineButton)
        self.fontLable = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.fontLable.setFont(font)
        self.fontLable.setObjectName("fontLable")
        self.horizontalLayout.addWidget(self.fontLable)
        self.fontComboBox = QtGui.QFontComboBox(self.frame)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout.addWidget(self.fontComboBox)
        self.fontSizeLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.fontSizeLabel.setFont(font)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.horizontalLayout.addWidget(self.fontSizeLabel)
        self.fontSizeComboBox = QtGui.QComboBox(self.frame)
        self.fontSizeComboBox.setObjectName("fontSizeComboBox")
        self.horizontalLayout.addWidget(self.fontSizeComboBox)
        self.undoButton = QtGui.QToolButton(self.frame)
        self.undoButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.undoButton.setFont(font)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout.addWidget(self.undoButton)
        self.redoButton = QtGui.QToolButton(self.frame)
        self.redoButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.redoButton.setFont(font)
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout.addWidget(self.redoButton)
        self.saveButton = QtGui.QToolButton(self.frame)
        self.saveButton.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.sourceTextBrowser = QtGui.QTextBrowser(self.SourceSummaryBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceTextBrowser.setFont(font)
        self.sourceTextBrowser.setObjectName("sourceTextBrowser")
        self.gridLayout_6.addWidget(self.sourceTextBrowser, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.SourceSummaryBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceSummaryFrame, 0, 1, 2, 1)
        sourceConnectMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sourceConnectMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        sourceConnectMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sourceConnectMainWindow)
        self.statusbar.setObjectName("statusbar")
        sourceConnectMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(sourceConnectMainWindow)
        self.toolBar.setObjectName("toolBar")
        sourceConnectMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.addTagAction = QtGui.QAction(sourceConnectMainWindow)
        self.addTagAction.setObjectName("addTagAction")
        self.addSourceAction = QtGui.QAction(sourceConnectMainWindow)
        self.addSourceAction.setObjectName("addSourceAction")
        self.loadDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.loadDatabaseAction.setObjectName("loadDatabaseAction")
        self.saveToDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.saveToDatabaseAction.setSoftKeyRole(QtGui.QAction.SelectSoftKey)
        self.saveToDatabaseAction.setPriority(QtGui.QAction.NormalPriority)
        self.saveToDatabaseAction.setObjectName("saveToDatabaseAction")
        self.actionDocumentation = QtGui.QAction(sourceConnectMainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.newDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.newDatabaseAction.setObjectName("newDatabaseAction")
        self.saveAsNewDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.saveAsNewDatabaseAction.setObjectName("saveAsNewDatabaseAction")
        self.fileMenu.addAction(self.addTagAction)
        self.fileMenu.addAction(self.addSourceAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.newDatabaseAction)
        self.fileMenu.addAction(self.loadDatabaseAction)
        self.fileMenu.addAction(self.saveToDatabaseAction)
        self.fileMenu.addAction(self.saveAsNewDatabaseAction)
        self.helpMenu.addAction(self.actionDocumentation)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(sourceConnectMainWindow)
        QtCore.QMetaObject.connectSlotsByName(sourceConnectMainWindow)
        sourceConnectMainWindow.setTabOrder(self.tagLineEdit, self.sourceLineEdit)
        sourceConnectMainWindow.setTabOrder(self.sourceLineEdit, self.superTagButton)
        sourceConnectMainWindow.setTabOrder(self.superTagButton, self.tagListWidget)
        sourceConnectMainWindow.setTabOrder(self.tagListWidget, self.sourcesList)
        sourceConnectMainWindow.setTabOrder(self.sourcesList, self.tagSearchButton)
        sourceConnectMainWindow.setTabOrder(self.tagSearchButton, self.sourcesSearchButton)
        sourceConnectMainWindow.setTabOrder(self.sourcesSearchButton, self.sourceTextBrowser)
        sourceConnectMainWindow.setTabOrder(self.sourceTextBrowser, self.subTagButton)
        sourceConnectMainWindow.setTabOrder(self.subTagButton, self.clearTagsButton)

    def retranslateUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setWindowTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "SourceConnect", None, QtGui.QApplication.UnicodeUTF8))
        self.tagBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.superTagButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Supertags of selected tags (all tags for which selections are subtags)", None, QtGui.QApplication.UnicodeUTF8))
        self.superTagButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", " Sup ↑", None, QtGui.QApplication.UnicodeUTF8))
        self.subTagButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Subtags of selected tags (all tags for which selections are supertags)", None, QtGui.QApplication.UnicodeUTF8))
        self.subTagButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "↓ Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.clearTagsButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Clear tag selection", None, QtGui.QApplication.UnicodeUTF8))
        self.clearTagsButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tagListWidget.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select one or more tags to view their associated sources. Double-click a tag to view its sub-tags.", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesList.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select one or more sources to view their contents", None, QtGui.QApplication.UnicodeUTF8))
        self.SourceSummaryBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Source Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Underlined", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.fontLable.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.fontComboBox.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select font", None, QtGui.QApplication.UnicodeUTF8))
        self.fontSizeLabel.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.fontSizeComboBox.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select font size", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "↶", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "↷", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.addTagAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.addSourceAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Source", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Load Database", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Save to Current Database", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.newDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "New Database", None, QtGui.QApplication.UnicodeUTF8))
        self.newDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+Shift+N", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsNewDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Save as New Database", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsNewDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))

