# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_tag_dialog.ui'
#
# Created: Mon Oct 31 22:33:39 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_editTagDialog(object):
    def setupUi(self, editTagDialog):
        editTagDialog.setObjectName("editTagDialog")
        editTagDialog.resize(824, 671)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        editTagDialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(editTagDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtGui.QFrame(editTagDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mainFrame.setFont(font)
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tagNameLabel = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagNameLabel.sizePolicy().hasHeightForWidth())
        self.tagNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.tagNameLabel.setFont(font)
        self.tagNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tagNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.tagNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tagNameLabel.setMargin(0)
        self.tagNameLabel.setIndent(0)
        self.tagNameLabel.setObjectName("tagNameLabel")
        self.verticalLayout.addWidget(self.tagNameLabel)
        self.tagNameLineEdit = QtGui.QLineEdit(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tagNameLineEdit.setFont(font)
        self.tagNameLineEdit.setObjectName("tagNameLineEdit")
        self.verticalLayout.addWidget(self.tagNameLineEdit)
        self.firstInnerFrame = QtGui.QFrame(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.firstInnerFrame.setFont(font)
        self.firstInnerFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.firstInnerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.firstInnerFrame.setObjectName("firstInnerFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.firstInnerFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.taggedSourcesGroupBox = QtGui.QGroupBox(self.firstInnerFrame)
        self.taggedSourcesGroupBox.setObjectName("taggedSourcesGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.taggedSourcesGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.taggedSourcesLineEdit = QtGui.QLineEdit(self.taggedSourcesGroupBox)
        self.taggedSourcesLineEdit.setObjectName("taggedSourcesLineEdit")
        self.gridLayout_3.addWidget(self.taggedSourcesLineEdit, 0, 2, 1, 1)
        self.taggedSourcesSearchButton = QtGui.QPushButton(self.taggedSourcesGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taggedSourcesSearchButton.setFont(font)
        self.taggedSourcesSearchButton.setObjectName("taggedSourcesSearchButton")
        self.gridLayout_3.addWidget(self.taggedSourcesSearchButton, 0, 3, 1, 1)
        self.taggedSourceRemoveButton = QtGui.QPushButton(self.taggedSourcesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taggedSourceRemoveButton.sizePolicy().hasHeightForWidth())
        self.taggedSourceRemoveButton.setSizePolicy(sizePolicy)
        self.taggedSourceRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taggedSourceRemoveButton.setFont(font)
        self.taggedSourceRemoveButton.setObjectName("taggedSourceRemoveButton")
        self.gridLayout_3.addWidget(self.taggedSourceRemoveButton, 0, 1, 1, 1)
        self.taggedSourcesList = QtGui.QListWidget(self.taggedSourcesGroupBox)
        self.taggedSourcesList.setObjectName("taggedSourcesList")
        self.gridLayout_3.addWidget(self.taggedSourcesList, 1, 0, 1, 4)
        self.taggedSourceAddButton = QtGui.QPushButton(self.taggedSourcesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taggedSourceAddButton.sizePolicy().hasHeightForWidth())
        self.taggedSourceAddButton.setSizePolicy(sizePolicy)
        self.taggedSourceAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taggedSourceAddButton.setFont(font)
        self.taggedSourceAddButton.setObjectName("taggedSourceAddButton")
        self.gridLayout_3.addWidget(self.taggedSourceAddButton, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.taggedSourcesGroupBox)
        self.relatedTagsGroupBox = QtGui.QGroupBox(self.firstInnerFrame)
        self.relatedTagsGroupBox.setObjectName("relatedTagsGroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.relatedTagsGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.relatedTagSearchButton = QtGui.QPushButton(self.relatedTagsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relatedTagSearchButton.setFont(font)
        self.relatedTagSearchButton.setObjectName("relatedTagSearchButton")
        self.gridLayout_4.addWidget(self.relatedTagSearchButton, 0, 3, 1, 1)
        self.relatedTagsLineEdit = QtGui.QLineEdit(self.relatedTagsGroupBox)
        self.relatedTagsLineEdit.setObjectName("relatedTagsLineEdit")
        self.gridLayout_4.addWidget(self.relatedTagsLineEdit, 0, 2, 1, 1)
        self.relatedTagRemoveButton = QtGui.QPushButton(self.relatedTagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relatedTagRemoveButton.sizePolicy().hasHeightForWidth())
        self.relatedTagRemoveButton.setSizePolicy(sizePolicy)
        self.relatedTagRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relatedTagRemoveButton.setFont(font)
        self.relatedTagRemoveButton.setObjectName("relatedTagRemoveButton")
        self.gridLayout_4.addWidget(self.relatedTagRemoveButton, 0, 1, 1, 1)
        self.relatedTagAddButton = QtGui.QPushButton(self.relatedTagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relatedTagAddButton.sizePolicy().hasHeightForWidth())
        self.relatedTagAddButton.setSizePolicy(sizePolicy)
        self.relatedTagAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relatedTagAddButton.setFont(font)
        self.relatedTagAddButton.setObjectName("relatedTagAddButton")
        self.gridLayout_4.addWidget(self.relatedTagAddButton, 0, 0, 1, 1)
        self.relatedTagsList = QtGui.QListWidget(self.relatedTagsGroupBox)
        self.relatedTagsList.setObjectName("relatedTagsList")
        self.gridLayout_4.addWidget(self.relatedTagsList, 1, 0, 1, 4)
        self.horizontalLayout_2.addWidget(self.relatedTagsGroupBox)
        self.verticalLayout.addWidget(self.firstInnerFrame)
        self.secondInnerFrame = QtGui.QFrame(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.secondInnerFrame.setFont(font)
        self.secondInnerFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.secondInnerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.secondInnerFrame.setObjectName("secondInnerFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.secondInnerFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.supertagsGroupBox = QtGui.QGroupBox(self.secondInnerFrame)
        self.supertagsGroupBox.setObjectName("supertagsGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.supertagsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.supertagSearchButton = QtGui.QPushButton(self.supertagsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supertagSearchButton.setFont(font)
        self.supertagSearchButton.setObjectName("supertagSearchButton")
        self.gridLayout_2.addWidget(self.supertagSearchButton, 0, 3, 1, 1)
        self.supertagsLineEdit = QtGui.QLineEdit(self.supertagsGroupBox)
        self.supertagsLineEdit.setObjectName("supertagsLineEdit")
        self.gridLayout_2.addWidget(self.supertagsLineEdit, 0, 2, 1, 1)
        self.supertagRemoveButton = QtGui.QPushButton(self.supertagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supertagRemoveButton.sizePolicy().hasHeightForWidth())
        self.supertagRemoveButton.setSizePolicy(sizePolicy)
        self.supertagRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supertagRemoveButton.setFont(font)
        self.supertagRemoveButton.setObjectName("supertagRemoveButton")
        self.gridLayout_2.addWidget(self.supertagRemoveButton, 0, 1, 1, 1)
        self.supertagAddButton = QtGui.QPushButton(self.supertagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supertagAddButton.sizePolicy().hasHeightForWidth())
        self.supertagAddButton.setSizePolicy(sizePolicy)
        self.supertagAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.supertagAddButton.setFont(font)
        self.supertagAddButton.setObjectName("supertagAddButton")
        self.gridLayout_2.addWidget(self.supertagAddButton, 0, 0, 1, 1)
        self.supertagsList = QtGui.QListWidget(self.supertagsGroupBox)
        self.supertagsList.setObjectName("supertagsList")
        self.gridLayout_2.addWidget(self.supertagsList, 1, 0, 1, 4)
        self.horizontalLayout.addWidget(self.supertagsGroupBox)
        self.subtagsGroupBox = QtGui.QGroupBox(self.secondInnerFrame)
        self.subtagsGroupBox.setObjectName("subtagsGroupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.subtagsGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.subtagSearchButton = QtGui.QPushButton(self.subtagsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subtagSearchButton.setFont(font)
        self.subtagSearchButton.setObjectName("subtagSearchButton")
        self.gridLayout_5.addWidget(self.subtagSearchButton, 0, 3, 1, 1)
        self.subtagsLineEdit = QtGui.QLineEdit(self.subtagsGroupBox)
        self.subtagsLineEdit.setObjectName("subtagsLineEdit")
        self.gridLayout_5.addWidget(self.subtagsLineEdit, 0, 2, 1, 1)
        self.subtagRemoveButton = QtGui.QPushButton(self.subtagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtagRemoveButton.sizePolicy().hasHeightForWidth())
        self.subtagRemoveButton.setSizePolicy(sizePolicy)
        self.subtagRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subtagRemoveButton.setFont(font)
        self.subtagRemoveButton.setObjectName("subtagRemoveButton")
        self.gridLayout_5.addWidget(self.subtagRemoveButton, 0, 1, 1, 1)
        self.subtagAddButton = QtGui.QPushButton(self.subtagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtagAddButton.sizePolicy().hasHeightForWidth())
        self.subtagAddButton.setSizePolicy(sizePolicy)
        self.subtagAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subtagAddButton.setFont(font)
        self.subtagAddButton.setObjectName("subtagAddButton")
        self.gridLayout_5.addWidget(self.subtagAddButton, 0, 0, 1, 1)
        self.subTagsList = QtGui.QListWidget(self.subtagsGroupBox)
        self.subTagsList.setObjectName("subTagsList")
        self.gridLayout_5.addWidget(self.subTagsList, 1, 0, 1, 4)
        self.horizontalLayout.addWidget(self.subtagsGroupBox)
        self.verticalLayout.addWidget(self.secondInnerFrame)
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)

        self.retranslateUi(editTagDialog)
        QtCore.QObject.connect(self.supertagsLineEdit, QtCore.SIGNAL("returnPressed()"), self.supertagSearchButton.click)
        QtCore.QObject.connect(self.subtagsLineEdit, QtCore.SIGNAL("returnPressed()"), self.subtagSearchButton.click)
        QtCore.QObject.connect(self.relatedTagsLineEdit, QtCore.SIGNAL("returnPressed()"), self.relatedTagSearchButton.click)
        QtCore.QObject.connect(self.taggedSourcesLineEdit, QtCore.SIGNAL("returnPressed()"), self.taggedSourcesSearchButton.click)
        QtCore.QMetaObject.connectSlotsByName(editTagDialog)

    def retranslateUi(self, editTagDialog):
        editTagDialog.setWindowTitle(QtGui.QApplication.translate("editTagDialog", "Edit Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.tagNameLabel.setText(QtGui.QApplication.translate("editTagDialog", "Tag Name", None, QtGui.QApplication.UnicodeUTF8))
        self.taggedSourcesGroupBox.setTitle(QtGui.QApplication.translate("editTagDialog", "Tagged Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.taggedSourcesSearchButton.setText(QtGui.QApplication.translate("editTagDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.taggedSourceRemoveButton.setText(QtGui.QApplication.translate("editTagDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.taggedSourceAddButton.setText(QtGui.QApplication.translate("editTagDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.relatedTagsGroupBox.setTitle(QtGui.QApplication.translate("editTagDialog", "Related Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.relatedTagSearchButton.setText(QtGui.QApplication.translate("editTagDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.relatedTagRemoveButton.setText(QtGui.QApplication.translate("editTagDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.relatedTagAddButton.setText(QtGui.QApplication.translate("editTagDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.supertagsGroupBox.setTitle(QtGui.QApplication.translate("editTagDialog", "Supertags", None, QtGui.QApplication.UnicodeUTF8))
        self.supertagSearchButton.setText(QtGui.QApplication.translate("editTagDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.supertagRemoveButton.setText(QtGui.QApplication.translate("editTagDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.supertagAddButton.setText(QtGui.QApplication.translate("editTagDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.subtagsGroupBox.setTitle(QtGui.QApplication.translate("editTagDialog", "Subtags", None, QtGui.QApplication.UnicodeUTF8))
        self.subtagSearchButton.setText(QtGui.QApplication.translate("editTagDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.subtagRemoveButton.setText(QtGui.QApplication.translate("editTagDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.subtagAddButton.setText(QtGui.QApplication.translate("editTagDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))

