# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_source_dialog.ui'
#
# Created: Wed Nov 09 16:43:55 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_editSourceDialog(object):
    def setupUi(self, editSourceDialog):
        editSourceDialog.setObjectName("editSourceDialog")
        editSourceDialog.resize(824, 671)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        editSourceDialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(editSourceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtGui.QFrame(editSourceDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mainFrame.setFont(font)
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sourceNameLabel = QtGui.QLabel(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceNameLabel.sizePolicy().hasHeightForWidth())
        self.sourceNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.sourceNameLabel.setFont(font)
        self.sourceNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sourceNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.sourceNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sourceNameLabel.setMargin(0)
        self.sourceNameLabel.setIndent(0)
        self.sourceNameLabel.setObjectName("sourceNameLabel")
        self.verticalLayout.addWidget(self.sourceNameLabel)
        self.sourceNameLineEdit = QtGui.QLineEdit(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sourceNameLineEdit.setFont(font)
        self.sourceNameLineEdit.setObjectName("sourceNameLineEdit")
        self.verticalLayout.addWidget(self.sourceNameLineEdit)
        self.firstInnerFrame = QtGui.QFrame(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.firstInnerFrame.setFont(font)
        self.firstInnerFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.firstInnerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.firstInnerFrame.setObjectName("firstInnerFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.firstInnerFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tagsGroupBox = QtGui.QGroupBox(self.firstInnerFrame)
        self.tagsGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tagsGroupBox.setObjectName("tagsGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.tagsGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tagLineEdit = QtGui.QLineEdit(self.tagsGroupBox)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.gridLayout_3.addWidget(self.tagLineEdit, 0, 2, 1, 1)
        self.tagsSearchButton = QtGui.QPushButton(self.tagsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tagsSearchButton.setFont(font)
        self.tagsSearchButton.setObjectName("tagsSearchButton")
        self.gridLayout_3.addWidget(self.tagsSearchButton, 0, 3, 1, 1)
        self.tagRemoveButton = QtGui.QPushButton(self.tagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagRemoveButton.sizePolicy().hasHeightForWidth())
        self.tagRemoveButton.setSizePolicy(sizePolicy)
        self.tagRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tagRemoveButton.setFont(font)
        self.tagRemoveButton.setObjectName("tagRemoveButton")
        self.gridLayout_3.addWidget(self.tagRemoveButton, 0, 1, 1, 1)
        self.tagsList = QtGui.QListWidget(self.tagsGroupBox)
        self.tagsList.setObjectName("tagsList")
        self.gridLayout_3.addWidget(self.tagsList, 1, 0, 1, 4)
        self.tagAddButton = QtGui.QPushButton(self.tagsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagAddButton.sizePolicy().hasHeightForWidth())
        self.tagAddButton.setSizePolicy(sizePolicy)
        self.tagAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tagAddButton.setFont(font)
        self.tagAddButton.setObjectName("tagAddButton")
        self.gridLayout_3.addWidget(self.tagAddButton, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.tagsGroupBox)
        self.filesGroupBox = QtGui.QGroupBox(self.firstInnerFrame)
        self.filesGroupBox.setObjectName("filesGroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.filesGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fileSearchButton = QtGui.QPushButton(self.filesGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fileSearchButton.setFont(font)
        self.fileSearchButton.setObjectName("fileSearchButton")
        self.gridLayout_4.addWidget(self.fileSearchButton, 0, 3, 1, 1)
        self.fileLineEdit = QtGui.QLineEdit(self.filesGroupBox)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.gridLayout_4.addWidget(self.fileLineEdit, 0, 2, 1, 1)
        self.fileRemoveButton = QtGui.QPushButton(self.filesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileRemoveButton.sizePolicy().hasHeightForWidth())
        self.fileRemoveButton.setSizePolicy(sizePolicy)
        self.fileRemoveButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fileRemoveButton.setFont(font)
        self.fileRemoveButton.setObjectName("fileRemoveButton")
        self.gridLayout_4.addWidget(self.fileRemoveButton, 0, 1, 1, 1)
        self.fileAddButton = QtGui.QPushButton(self.filesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileAddButton.sizePolicy().hasHeightForWidth())
        self.fileAddButton.setSizePolicy(sizePolicy)
        self.fileAddButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fileAddButton.setFont(font)
        self.fileAddButton.setObjectName("fileAddButton")
        self.gridLayout_4.addWidget(self.fileAddButton, 0, 0, 1, 1)
        self.fileList = QtGui.QListWidget(self.filesGroupBox)
        self.fileList.setObjectName("fileList")
        self.gridLayout_4.addWidget(self.fileList, 1, 0, 1, 4)
        self.horizontalLayout_2.addWidget(self.filesGroupBox)
        self.verticalLayout.addWidget(self.firstInnerFrame)
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)

        self.retranslateUi(editSourceDialog)
        QtCore.QObject.connect(self.fileLineEdit, QtCore.SIGNAL("returnPressed()"), self.fileSearchButton.click)
        QtCore.QObject.connect(self.tagLineEdit, QtCore.SIGNAL("returnPressed()"), self.tagsSearchButton.click)
        QtCore.QMetaObject.connectSlotsByName(editSourceDialog)

    def retranslateUi(self, editSourceDialog):
        editSourceDialog.setWindowTitle(QtGui.QApplication.translate("editSourceDialog", "Edit Source", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceNameLabel.setText(QtGui.QApplication.translate("editSourceDialog", "Source Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsGroupBox.setTitle(QtGui.QApplication.translate("editSourceDialog", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsSearchButton.setText(QtGui.QApplication.translate("editSourceDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tagRemoveButton.setText(QtGui.QApplication.translate("editSourceDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tagAddButton.setText(QtGui.QApplication.translate("editSourceDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.filesGroupBox.setTitle(QtGui.QApplication.translate("editSourceDialog", "Associated Files", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSearchButton.setText(QtGui.QApplication.translate("editSourceDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.fileRemoveButton.setText(QtGui.QApplication.translate("editSourceDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.fileAddButton.setText(QtGui.QApplication.translate("editSourceDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))

