# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun Oct 16 20:00:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_sourceConnectMainWindow(object):
    def setupUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setObjectName("sourceConnectMainWindow")
        sourceConnectMainWindow.resize(1045, 834)
        self.centralwidget = QtGui.QWidget(sourceConnectMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sourceContentFrame = QtGui.QFrame(self.centralwidget)
        self.sourceContentFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourceContentFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourceContentFrame.setObjectName("sourceContentFrame")
        self.gridLayout_3 = QtGui.QGridLayout(self.sourceContentFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sourceContentBox = QtGui.QGroupBox(self.sourceContentFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.sourceContentBox.setFont(font)
        self.sourceContentBox.setFlat(False)
        self.sourceContentBox.setCheckable(False)
        self.sourceContentBox.setObjectName("sourceContentBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.sourceContentBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.sourceContentLineEdit = QtGui.QLineEdit(self.sourceContentBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceContentLineEdit.setFont(font)
        self.sourceContentLineEdit.setObjectName("sourceContentLineEdit")
        self.gridLayout_9.addWidget(self.sourceContentLineEdit, 0, 0, 1, 1)
        self.sourceContentList = QtGui.QListWidget(self.sourceContentBox)
        self.sourceContentList.setObjectName("sourceContentList")
        self.gridLayout_9.addWidget(self.sourceContentList, 1, 0, 1, 3)
        self.sourceContentSearchButton = QtGui.QPushButton(self.sourceContentBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceContentSearchButton.setFont(font)
        self.sourceContentSearchButton.setObjectName("sourceContentSearchButton")
        self.gridLayout_9.addWidget(self.sourceContentSearchButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.sourceContentBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceContentFrame, 2, 0, 1, 1)
        self.tagFrame = QtGui.QFrame(self.centralwidget)
        self.tagFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tagFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tagFrame.setObjectName("tagFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.tagFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagBox = QtGui.QGroupBox(self.tagFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.tagBox.setFont(font)
        self.tagBox.setFlat(False)
        self.tagBox.setCheckable(False)
        self.tagBox.setObjectName("tagBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.tagBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tagLineEdit = QtGui.QLineEdit(self.tagBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagLineEdit.setFont(font)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.gridLayout_8.addWidget(self.tagLineEdit, 0, 0, 1, 1)
        self.tagSearchButton = QtGui.QPushButton(self.tagBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagSearchButton.setFont(font)
        self.tagSearchButton.setObjectName("tagSearchButton")
        self.gridLayout_8.addWidget(self.tagSearchButton, 0, 1, 1, 1)
        self.tagListWidget = QtGui.QListWidget(self.tagBox)
        self.tagListWidget.setObjectName("tagListWidget")
        self.gridLayout_8.addWidget(self.tagListWidget, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.tagBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.tagFrame, 0, 0, 1, 1)
        self.sourcesFrame = QtGui.QFrame(self.centralwidget)
        self.sourcesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourcesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourcesFrame.setObjectName("sourcesFrame")
        self.gridLayout_5 = QtGui.QGridLayout(self.sourcesFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sourcesBox = QtGui.QGroupBox(self.sourcesFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.sourcesBox.setFont(font)
        self.sourcesBox.setFlat(False)
        self.sourcesBox.setCheckable(False)
        self.sourcesBox.setObjectName("sourcesBox")
        self.gridLayout_7 = QtGui.QGridLayout(self.sourcesBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.sourcesList = QtGui.QListWidget(self.sourcesBox)
        self.sourcesList.setObjectName("sourcesList")
        self.gridLayout_7.addWidget(self.sourcesList, 1, 0, 1, 3)
        self.sourceLineEdit = QtGui.QLineEdit(self.sourcesBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceLineEdit.setFont(font)
        self.sourceLineEdit.setObjectName("sourceLineEdit")
        self.gridLayout_7.addWidget(self.sourceLineEdit, 0, 0, 1, 1)
        self.sourcesSearchButton = QtGui.QPushButton(self.sourcesBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourcesSearchButton.setFont(font)
        self.sourcesSearchButton.setObjectName("sourcesSearchButton")
        self.gridLayout_7.addWidget(self.sourcesSearchButton, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.sourcesBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourcesFrame, 0, 1, 1, 1)
        self.sourceSummaryFrame = QtGui.QFrame(self.centralwidget)
        self.sourceSummaryFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourceSummaryFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourceSummaryFrame.setObjectName("sourceSummaryFrame")
        self.gridLayout_4 = QtGui.QGridLayout(self.sourceSummaryFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SourceSummaryBox = QtGui.QGroupBox(self.sourceSummaryFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.SourceSummaryBox.setFont(font)
        self.SourceSummaryBox.setFlat(False)
        self.SourceSummaryBox.setCheckable(False)
        self.SourceSummaryBox.setObjectName("SourceSummaryBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.SourceSummaryBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sourceTextBrowser = QtGui.QTextBrowser(self.SourceSummaryBox)
        self.sourceTextBrowser.setObjectName("sourceTextBrowser")
        self.gridLayout_6.addWidget(self.sourceTextBrowser, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.SourceSummaryBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceSummaryFrame, 2, 1, 1, 1)
        sourceConnectMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sourceConnectMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        sourceConnectMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sourceConnectMainWindow)
        self.statusbar.setObjectName("statusbar")
        sourceConnectMainWindow.setStatusBar(self.statusbar)
        self.addTagAction = QtGui.QAction(sourceConnectMainWindow)
        self.addTagAction.setObjectName("addTagAction")
        self.addSourceAction = QtGui.QAction(sourceConnectMainWindow)
        self.addSourceAction.setObjectName("addSourceAction")
        self.fileMenu.addAction(self.addTagAction)
        self.fileMenu.addAction(self.addSourceAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(sourceConnectMainWindow)
        QtCore.QMetaObject.connectSlotsByName(sourceConnectMainWindow)

    def retranslateUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setWindowTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "SourceConnect", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Source Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Type source content name here and press search", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tagBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Type tag name here and press search", None, QtGui.QApplication.UnicodeUTF8))
        self.tagSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Type source name here and press search", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.SourceSummaryBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Source Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.addTagAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.addSourceAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Source", None, QtGui.QApplication.UnicodeUTF8))

