# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_qt.ui'
#
# Created: Sun Oct 23 22:57:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_sourceConnectMainWindow(object):
    def setupUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setObjectName("sourceConnectMainWindow")
        sourceConnectMainWindow.resize(1045, 834)
        self.centralwidget = QtGui.QWidget(sourceConnectMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sourceContentFrame = QtGui.QFrame(self.centralwidget)
        self.sourceContentFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourceContentFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourceContentFrame.setObjectName("sourceContentFrame")
        self.gridLayout_3 = QtGui.QGridLayout(self.sourceContentFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sourceContentBox = QtGui.QGroupBox(self.sourceContentFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.sourceContentBox.setFont(font)
        self.sourceContentBox.setFlat(False)
        self.sourceContentBox.setCheckable(False)
        self.sourceContentBox.setObjectName("sourceContentBox")
        self.gridLayout_9 = QtGui.QGridLayout(self.sourceContentBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.sourceContentLineEdit = QtGui.QLineEdit(self.sourceContentBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceContentLineEdit.setFont(font)
        self.sourceContentLineEdit.setObjectName("sourceContentLineEdit")
        self.gridLayout_9.addWidget(self.sourceContentLineEdit, 0, 0, 1, 1)
        self.sourceContentList = QtGui.QListWidget(self.sourceContentBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sourceContentList.setFont(font)
        self.sourceContentList.setObjectName("sourceContentList")
        self.gridLayout_9.addWidget(self.sourceContentList, 1, 0, 1, 3)
        self.sourceContentSearchButton = QtGui.QPushButton(self.sourceContentBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceContentSearchButton.setFont(font)
        self.sourceContentSearchButton.setObjectName("sourceContentSearchButton")
        self.gridLayout_9.addWidget(self.sourceContentSearchButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.sourceContentBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceContentFrame, 2, 0, 1, 1)
        self.tagFrame = QtGui.QFrame(self.centralwidget)
        self.tagFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tagFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tagFrame.setObjectName("tagFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.tagFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagBox = QtGui.QGroupBox(self.tagFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.tagBox.setFont(font)
        self.tagBox.setFlat(False)
        self.tagBox.setCheckable(False)
        self.tagBox.setObjectName("tagBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.tagBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tagLineEdit = QtGui.QLineEdit(self.tagBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagLineEdit.setFont(font)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.gridLayout_8.addWidget(self.tagLineEdit, 0, 2, 1, 1)
        self.tagSearchButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagSearchButton.sizePolicy().hasHeightForWidth())
        self.tagSearchButton.setSizePolicy(sizePolicy)
        self.tagSearchButton.setMinimumSize(QtCore.QSize(45, 0))
        self.tagSearchButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagSearchButton.setFont(font)
        self.tagSearchButton.setObjectName("tagSearchButton")
        self.gridLayout_8.addWidget(self.tagSearchButton, 0, 3, 1, 1)
        self.superTagButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.superTagButton.sizePolicy().hasHeightForWidth())
        self.superTagButton.setSizePolicy(sizePolicy)
        self.superTagButton.setMinimumSize(QtCore.QSize(45, 0))
        self.superTagButton.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.superTagButton.setFont(font)
        self.superTagButton.setStatusTip("")
        self.superTagButton.setObjectName("superTagButton")
        self.gridLayout_8.addWidget(self.superTagButton, 0, 0, 1, 1)
        self.subTagButton = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subTagButton.sizePolicy().hasHeightForWidth())
        self.subTagButton.setSizePolicy(sizePolicy)
        self.subTagButton.setMinimumSize(QtCore.QSize(45, 0))
        self.subTagButton.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.subTagButton.setFont(font)
        self.subTagButton.setStatusTip("")
        self.subTagButton.setObjectName("subTagButton")
        self.gridLayout_8.addWidget(self.subTagButton, 0, 1, 1, 1)
        self.tagSearchButton_2 = QtGui.QPushButton(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagSearchButton_2.sizePolicy().hasHeightForWidth())
        self.tagSearchButton_2.setSizePolicy(sizePolicy)
        self.tagSearchButton_2.setMinimumSize(QtCore.QSize(45, 0))
        self.tagSearchButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tagSearchButton_2.setFont(font)
        self.tagSearchButton_2.setObjectName("tagSearchButton_2")
        self.gridLayout_8.addWidget(self.tagSearchButton_2, 0, 4, 1, 1)
        self.tagListWidget = QtGui.QListWidget(self.tagBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagListWidget.sizePolicy().hasHeightForWidth())
        self.tagListWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tagListWidget.setFont(font)
        self.tagListWidget.setObjectName("tagListWidget")
        self.gridLayout_8.addWidget(self.tagListWidget, 1, 0, 1, 5)
        self.gridLayout_2.addWidget(self.tagBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.tagFrame, 0, 0, 1, 1)
        self.sourcesFrame = QtGui.QFrame(self.centralwidget)
        self.sourcesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourcesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourcesFrame.setObjectName("sourcesFrame")
        self.gridLayout_5 = QtGui.QGridLayout(self.sourcesFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sourcesBox = QtGui.QGroupBox(self.sourcesFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.sourcesBox.setFont(font)
        self.sourcesBox.setFlat(False)
        self.sourcesBox.setCheckable(False)
        self.sourcesBox.setObjectName("sourcesBox")
        self.gridLayout_7 = QtGui.QGridLayout(self.sourcesBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.sourcesList = QtGui.QListWidget(self.sourcesBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sourcesList.setFont(font)
        self.sourcesList.setObjectName("sourcesList")
        self.gridLayout_7.addWidget(self.sourcesList, 1, 0, 1, 3)
        self.sourceLineEdit = QtGui.QLineEdit(self.sourcesBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceLineEdit.setFont(font)
        self.sourceLineEdit.setObjectName("sourceLineEdit")
        self.gridLayout_7.addWidget(self.sourceLineEdit, 0, 0, 1, 1)
        self.sourcesSearchButton = QtGui.QPushButton(self.sourcesBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourcesSearchButton.setFont(font)
        self.sourcesSearchButton.setObjectName("sourcesSearchButton")
        self.gridLayout_7.addWidget(self.sourcesSearchButton, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.sourcesBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourcesFrame, 0, 1, 1, 1)
        self.sourceSummaryFrame = QtGui.QFrame(self.centralwidget)
        self.sourceSummaryFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sourceSummaryFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sourceSummaryFrame.setObjectName("sourceSummaryFrame")
        self.gridLayout_4 = QtGui.QGridLayout(self.sourceSummaryFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SourceSummaryBox = QtGui.QGroupBox(self.sourceSummaryFrame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.SourceSummaryBox.setFont(font)
        self.SourceSummaryBox.setFlat(False)
        self.SourceSummaryBox.setCheckable(False)
        self.SourceSummaryBox.setObjectName("SourceSummaryBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.SourceSummaryBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sourceTextBrowser = QtGui.QTextBrowser(self.SourceSummaryBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.sourceTextBrowser.setFont(font)
        self.sourceTextBrowser.setObjectName("sourceTextBrowser")
        self.gridLayout_6.addWidget(self.sourceTextBrowser, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.SourceSummaryBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceSummaryFrame, 2, 1, 1, 1)
        sourceConnectMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sourceConnectMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        sourceConnectMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sourceConnectMainWindow)
        self.statusbar.setObjectName("statusbar")
        sourceConnectMainWindow.setStatusBar(self.statusbar)
        self.addTagAction = QtGui.QAction(sourceConnectMainWindow)
        self.addTagAction.setObjectName("addTagAction")
        self.addSourceAction = QtGui.QAction(sourceConnectMainWindow)
        self.addSourceAction.setObjectName("addSourceAction")
        self.loadDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.loadDatabaseAction.setObjectName("loadDatabaseAction")
        self.saveToDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.saveToDatabaseAction.setSoftKeyRole(QtGui.QAction.SelectSoftKey)
        self.saveToDatabaseAction.setPriority(QtGui.QAction.NormalPriority)
        self.saveToDatabaseAction.setObjectName("saveToDatabaseAction")
        self.actionDocumentation = QtGui.QAction(sourceConnectMainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.newDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.newDatabaseAction.setObjectName("newDatabaseAction")
        self.saveAsNewDatabaseAction = QtGui.QAction(sourceConnectMainWindow)
        self.saveAsNewDatabaseAction.setObjectName("saveAsNewDatabaseAction")
        self.fileMenu.addAction(self.addTagAction)
        self.fileMenu.addAction(self.addSourceAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.newDatabaseAction)
        self.fileMenu.addAction(self.loadDatabaseAction)
        self.fileMenu.addAction(self.saveToDatabaseAction)
        self.fileMenu.addAction(self.saveAsNewDatabaseAction)
        self.helpMenu.addAction(self.actionDocumentation)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(sourceConnectMainWindow)
        QtCore.QMetaObject.connectSlotsByName(sourceConnectMainWindow)
        sourceConnectMainWindow.setTabOrder(self.tagLineEdit, self.sourceLineEdit)
        sourceConnectMainWindow.setTabOrder(self.sourceLineEdit, self.sourceContentLineEdit)
        sourceConnectMainWindow.setTabOrder(self.sourceContentLineEdit, self.sourceContentList)
        sourceConnectMainWindow.setTabOrder(self.sourceContentList, self.superTagButton)
        sourceConnectMainWindow.setTabOrder(self.superTagButton, self.tagListWidget)
        sourceConnectMainWindow.setTabOrder(self.tagListWidget, self.sourcesList)
        sourceConnectMainWindow.setTabOrder(self.sourcesList, self.tagSearchButton)
        sourceConnectMainWindow.setTabOrder(self.tagSearchButton, self.sourcesSearchButton)
        sourceConnectMainWindow.setTabOrder(self.sourcesSearchButton, self.sourceTextBrowser)
        sourceConnectMainWindow.setTabOrder(self.sourceTextBrowser, self.subTagButton)
        sourceConnectMainWindow.setTabOrder(self.subTagButton, self.tagSearchButton_2)
        sourceConnectMainWindow.setTabOrder(self.tagSearchButton_2, self.sourceContentSearchButton)

    def retranslateUi(self, sourceConnectMainWindow):
        sourceConnectMainWindow.setWindowTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "SourceConnect", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Source Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search contents of selected source", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentList.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Double click content item to open it", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceContentSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tagBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tagSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.superTagButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Supertags of selected tags (all tags for which selections are subtags)", None, QtGui.QApplication.UnicodeUTF8))
        self.superTagButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", " Sup ↑", None, QtGui.QApplication.UnicodeUTF8))
        self.subTagButton.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Subtags of selected tags (all tags for which selections are supertags)", None, QtGui.QApplication.UnicodeUTF8))
        self.subTagButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "↓ Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.tagSearchButton_2.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tagListWidget.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select one or more tags to view their associated sources. Double-click a tag to view its sub-tags.", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesList.setToolTip(QtGui.QApplication.translate("sourceConnectMainWindow", "Select one or more sources to view their contents", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLineEdit.setPlaceholderText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcesSearchButton.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.SourceSummaryBox.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Source Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("sourceConnectMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.addTagAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.addTagAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.addSourceAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Add Source", None, QtGui.QApplication.UnicodeUTF8))
        self.addSourceAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Load Database", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Save to Current Database", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.newDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "New Database", None, QtGui.QApplication.UnicodeUTF8))
        self.newDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsNewDatabaseAction.setText(QtGui.QApplication.translate("sourceConnectMainWindow", "Save as New Database", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsNewDatabaseAction.setShortcut(QtGui.QApplication.translate("sourceConnectMainWindow", "Ctrl+Shift+N", None, QtGui.QApplication.UnicodeUTF8))

